### GET all movies
GET http://localhost:8080/api/movies
Content-Type: application/json

### GET all employees
GET http://localhost:8080/api/employees
Content-Type: application/json

### GET all movies by age rating

GET http://localhost:8080/api/movies/by-age/12

### GET all equipment

GET http://localhost:8080/api/equipment/

### GET equipment by Id

GET http://localhost:8080/api/equipment/2

### GET all movies by rating

GET http://localhost:8080/api/movies/sorted-by-rating

### GET all employees who sold more than X tickets

GET http://localhost:8080/api/employees/sold-more-than-tickets/2
Content-Type: */*

### GET all customers
GET http://localhost:8080/api/customers

### GET all customers by favourite genre
GET http://localhost:8080/api/customers/byGenre/HORROR

### GET movie by id
GET http://localhost:8080/api/movies/1

### GET shortest movie by genre
GET http://localhost:8080/api/movies/shortest-movie-by-genre/ANIMATION

### GET most wealthiest customers
GET http://localhost:8080/api/customers/mostWealthiest

### CREATE new movie
POST http://localhost:8080/api/movies
Content-Type: application/json

{
  "title": "Inception",
  "duration": 148,
  "ageRating": 12,
  "description": "A mind-bending thriller by Christopher Nolan.",
  "releaseDate": 2010,
  "genre": {
    "id": 1
  }
}

### UPDATE existing Movie

PUT http://localhost:8080/api/movies/11
Content-Type: application/json

{
  "title": "Inception - Director's Cut",
  "duration": 152,
  "ageRating": 12,
  "description": "Extended version of the mind-bending thriller.",
  "releaseDate": 2010,
  "genre": {
    "id": 1
  }
}

### DELETE existing Movie

DELETE http://localhost:8080/api/movies/11
Content-Type: */*


